version: "3.8"

services:
  main-car:
    build:
      context: ./srcs/MainCar
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./srcs/MainCar
        target: /workspace

  controller:
    build:
      context: ./srcs/Controller
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./srcs/Controller
        target: /workspace
      - type: bind
        source: ../jetson-sysroot
        target: /opt/jetson-sysroot
    depends_on:
      - main-car
